# === Variables ===
@host = http://localhost:8080
@token = 8mfyBlEyqZjFWRDnmjPNJHkQofPoX4sQD1CGkIOsUN8=
@token2 = nBZ6YdMxlDn3nt6QR34xbH0W9KMVqH1J96YkBHAqk24=
@invite_token = TEST-INVITE-GAMMA
@lobbyId = 5
@gameId = 9
@roundNumber = 2

### Create User
POST {{host}}/user/create
Content-Type: application/json
Authorization: invite {{invite_token}}

{
"name": "Diogo Oliveira",
"nickName": "Diogo",
"email": "diogo@example.com",
"password": "Mypassword1",
"imageUrl": "https://example.com/avatar.png"
}


### other user
POST {{host}}/user/create
Content-Type: application/json
Authorization: invite {{invite_token}}

{
  "name": "Paulo",
  "nickName": "Paulo",
  "email": "Paulo@example.com",
  "password": "Mypassword1",
  "imageUrl": "https://example.com/avatar.png"
}

### Login User
POST {{host}}/user/login
Content-Type: application/json

{
"email": "diogo@example.com",
"password": "Mypassword1"
}



### other user
POST {{host}}/user/login
Content-Type: application/json

{
"email": "Paulo@example.com",
"password": "Mypassword1"
}

> {% client.global.set("token2", response.body.token) %}

### Create Lobby
POST {{host}}/lobbies/create
Content-Type: application/json
Authorization: Bearer {{token}}

{
"name": "Weekend Game",
"maxPlayers": 3,
"rounds": 12
}

> {% client.global.set("lobbyId", response.body.id) %}

### SSEEvents
GET {{host}}/lobbies/{{lobbyId}}/events
Authorization: Bearer {{token2}}

### Join Lobby
POST {{host}}/lobbies/join/{{lobbyId}}
Authorization: Bearer {{token2}}

### View Lobby Details
GET {{host}}/lobbies/{{lobbyId}}
Authorization: Bearer {{token}}

> {% client.global.set("gameId", response.body.gameId) %}

### View Game Info
### GET {{host}}/game/{{gameId}}
### Authorization: Bearer {{token}}

### Start Round
POST {{host}}/game/{{gameId}}/round/start
Authorization: Bearer {{token}}

> {% client.global.set("roundNumber", response.body.roundNumber) %}

### Get Player Hand
GET {{host}}/game/{{gameId}}/player/hand
Authorization: Bearer {{token}}

### Shuffle Dice
POST {{host}}/game/{{gameId}}/player/shuffle
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "lockedDice": [2,3]
}
### Shuffle Dice (example move)
POST {{host}}/game/{{gameId}}/player/shuffle
Content-Type: application/json
Authorization: Bearer {{token}}

{
"lockedDice": [0,1,2]
}

### Shuffle Dice other user
POST {{host}}/game/{{gameId}}/player/shuffle
Content-Type: application/json
Authorization: Bearer {{token2}}

{
  "lockedDice": []
}

### Finish Turn
PUT {{host}}/game/{{gameId}}/player/finish
Authorization: Bearer {{token}}

### Finish Turn
PUT {{host}}/game/{{gameId}}/player/finish
Authorization: Bearer {{token2}}

### Get Round Winner
GET {{host}}/game/{{gameId}}/round/winner
Authorization: Bearer {{token}}

### View Current Scores
GET {{host}}/game/{{gameId}}/scores
Authorization: Bearer {{token}}

### Get Game Winner
PATCH {{host}}/game/{{gameId}}/winner
Authorization: Bearer {{token2}}
